// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOj0VNbv_f2UtwPgW0_w5chBEwUPn2xy0',
    appId: '1:529567884336:web:03ab5520a3cfdbf38bf9f5',
    messagingSenderId: '529567884336',
    projectId: 'instagram-clone-94c30',
    authDomain: 'instagram-clone-94c30.firebaseapp.com',
    storageBucket: 'instagram-clone-94c30.appspot.com',
    measurementId: 'G-P29998NZ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW17OmEvMr45o42WtYA8onhdrfguz3u5U',
    appId: '1:529567884336:android:7714b842e31e07708bf9f5',
    messagingSenderId: '529567884336',
    projectId: 'instagram-clone-94c30',
    storageBucket: 'instagram-clone-94c30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIFOsJmSg3bvW4YToceCO7NKkQRCf-3Zk',
    appId: '1:529567884336:ios:038fa52cc16cf22a8bf9f5',
    messagingSenderId: '529567884336',
    projectId: 'instagram-clone-94c30',
    storageBucket: 'instagram-clone-94c30.appspot.com',
    iosClientId: '529567884336-5i3q1u3fhfq4j8k490stfj8h3lun8pnb.apps.googleusercontent.com',
    iosBundleId: 'com.insta.clone.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIFOsJmSg3bvW4YToceCO7NKkQRCf-3Zk',
    appId: '1:529567884336:ios:038fa52cc16cf22a8bf9f5',
    messagingSenderId: '529567884336',
    projectId: 'instagram-clone-94c30',
    storageBucket: 'instagram-clone-94c30.appspot.com',
    iosClientId: '529567884336-5i3q1u3fhfq4j8k490stfj8h3lun8pnb.apps.googleusercontent.com',
    iosBundleId: 'com.insta.clone.instagramClone',
  );
}
